name: 🐞 Bug report
about: Create a report to help us improve
title: ''
labels: ['bug']
assignees: ''

body:
  - type: textarea
    id: description
    attributes:
      label: Describe the Bug
      description: What happened? *(A clear and concise description)*
      placeholder: Your description here.
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: What is the severity of the bug according to you?
      multiple: false
      options:
        - Trivial (typos, etc)
        - Low (formatting issues, things that don't impact operation)
        - Medium (minor functional impact)
        - High (a broken feature, major functional impact)
        - Critical (bot crash, extremely major functional impact)
      validations:
        required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: What was the run command that triggered the bug?
      placeholder: '!ping'
      render: shell

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: To Reproduce
      description: 'Indicate here the steps to reproduce this bug:'
      value: |
        1.
        2.
        3.
        ...

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: '...'

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: '...'

  - type: checkboxes
    id: terms
    attributes:
      label: Bot's Permissions
      description: Errors can occur if you disabled some of the bot's permissions. Please verify that all the required permissions are enabled.
      options:
        - label: I confirm that I checked the bot's permissions
          required: true
