name: 🐛 Bug report
description: Report incorrect or unexpected behavior of the bot
labels: [bug]

body:
  - type: input
    id: command
    attributes:
      label: Which command was used?
      placeholder: '/roll alien dice:5 maxpush:0 private:true'

  - type: textarea
    id: description
    attributes:
      label: Issue Description
      description: |
        Describe the issue in as much detail as possible

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files into it.
      placeholder: |
        Steps to reproduce:
        1. use command
        2. do things
        3. observe behavior
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Priority this issue should have?
      description: Please be realistic. If you need to elaborate on your reasoning, please use the Issue description field above.
      multiple: false
      options:
        - Trivial (typos, etc)
        - Low (formatting issues, things that don't impact operation)
        - Medium (minor functional impact)
        - High (a broken feature, major functional impact)
        - Critical (bot crash, extremely major functional impact)

  - type: checkboxes
    id: terms
    attributes:
      label: Bot's Permissions
      description: Errors can occur if you disabled some of the bot's permissions. Please verify that all the required permissions are enabled.
      options:
        - label: I confirm that I checked the bot's permissions
          required: true
