name: 🚀 Feature request
description: Suggest an idea for this bot
labels: [enhancement]

body:
  - type: textarea
    id: relationship
    attributes:
      label: Is your feature request related to a problem? Please describe
      description: A clear and concise description of what the problem is.
      placeholder: '...'
    validations:
      required: true

  - type: textarea
    id: users
    attributes:
      label: Who would use it?
      description: The use case for this feature.
      placeholder: '...'
    validations:
      required: true

  - type: textarea
    id: bot-part
    attributes:
      label: What part of the bot?
      description: Initiative, dice roller, general functionality, commands aliasing.
      placeholder: '...'
    validations:
      required: true

  - type: textarea
    id: syntax
    attributes:
      label: How would it work?
      description: This is where you put the syntax/command.
      placeholder: '...'
    validations:
      required: true

  - type: textarea
    id: justify
    attributes:
      label: Why should this be added?
      description: Justify why you think it'd help others.
      placeholder: '...'
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
      placeholder: '...'
